### ISSUE TITLE
Crash on startup 1.21.1

### ISSUE THREAD

**Issue by TinyMandalorian** [Sindarin27/Farsighted-Mobs#16]
23:51:08] [main/INFO]: ThreadTweak config initialized
[23:51:17] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: Class net.minecraft.class_5134 does not have member field 'net.minecraft.class_1320 field_23717'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.class_5134 does not have member field 'net.minecraft.class_1320 field_23717'
        at knot/net.minecraft.class_1588.handler$bjn000$farsighted-mobs$createAttributes(class_1588.java:519) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1588.method_26918(class_1588.java:116) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1545.method_26906(class_1545.java:61) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_5135.<clinit>(class_5135.java:97) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_17598(class_2966.java:134) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more

**Comment by Sindarin27** [comment]
Which version of the mod are you using? Could you share the full crash report and latest.log?
